---
language: generic
dist: trusty
sudo: required
services:
  - docker
env:
  global:
  - secure: "3PJ9G6XSd9cguAdKTfc6WLissGuICiG+aVicayG/yXNDWUxAIuiziUpdZDTs65C21VvXS9emuYTwImDlAI2JDsme7+kGiudHvDBFQLLYKP8Tgj0IjdrkJRscrAg1yrw4Z9s63a7siZ+GlqLx5Ix1r2nfLWwu6P8TdKq6B9AiZGQPDFrWbT7xCmpOmEN7LmpYS5sm4o/FmAMk8iohMmVSkhlFrxkXLEW3MO307BS3RyqRonzFfjI3hVgvjroqN5pU+dOBM2hd276SWuIIVPJwKa2RLB7z0zFXbHmle9W2GGziFAsPDb9E8Pb2uiCgHscKUZ9vPtlOAGUkPOfOm/rjkG4RjXAyvlf/Ea4P2RR15yA7EKrQn4DHFiWjG02Own1Eh3PBZr4Gww1rdQKEq79GP6i/O61Bnv9CCtQ/1Na1FXznhqZ+QGxUcN1qUqMBC41hlOkXLfW3hxOKzg3vQYOFFeEeJJ+22DejENcHHWAFV3DzzM+hShkvwAhGPms3QTgP0bQUib04Meenb9QpNiIHUPqIdU3rSQ1SBkIt6zcTeZZ34wJyoU1nTuBCLdwAkRCsrflc8ZdLiZxwkciXWE5/hVq1UdpegkQAHd9QzzwRG/KgBQ8ViaNC9uCdqAYUsquJu+YzRO9TH47aBKBYyVt7oHoxpCx0BexX1NIuVuhhyP0="
  - secure: "1LcXOk5eaaBG3coDOMkgDHeUI89QBgrUgV2zflviL+MZoR9TsuVS5nf1MKHT7Flrwi8DsEeUUBiNBQZ14EiNIijt6U5AuGpL2+vJuZQCycRgFCAwQ5YJV7Q+XesHkBOMxZa2oiGjbPfaWT/jUOMI7JLnocYISGxA4d0tbW+8vZ4BPciaiF0Prb2MzY/ddZZW9gXSZ7xoMc6BoLODB2FrzEj6rfP41zAcwnihKojPd4UOU8rX+JBpxqXo5zYU5msw6vi7Po+CwTEuR2kfl5O2Rx67JVHOGSNWA0kB4tMlB+zDEJKqbUkvrMu7a+UlTLbcroxC7zoVB2tfpxL6IqdYLqMHbgIJAMOiNvPgcuoWDt5U6wOj3upO2hR+MQkRGDfhzyLrEqCA5CdKTVBCIqy5bwaHyQoqajR1cQuUUQ3akTC5Syg/fb5Ms9U5/IdlFeyEG9R+s+ht6fDELENzfA9VwiiZIEo1rToS1ofpofEpm8RHtwA9jMxHdh8R6mtaDrFBL5KPmoyX4TjxxA/LYsATkdluL3mSrx0F+Rrs8zabVdkWq9bKlY0AjttEOGrAeBzqmieHBLzPPslpG/k2hdIObrPvD8X1dWR7jcSdIrcTEsxs8p1UAGohJYm+StNrY2C6WGDhm4AX0KdV9ZE/jdwIflt1Vt+UipXczIjLajgq7M4="

before_install:
- docker --version
- docker-compose --version

install:
- curl -L https://goss.rocks/install | sudo sh
- sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- ecs-cli configure profile --profile-name travis --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY
- ecs-cli configure --cluster default --default-launch-type EC2 --region eu-central-1 --config-name travis

script:
- /bin/bash docker/label_containers.sh &&
  docker-compose -p smartzplatform build &&
  /bin/bash ./tests/integration.sh &&
  docker images &&
  /bin/bash ./docker/upload_to_registry.sh smartzplatform_frontend smartzplatform_backend

notifications:
  email:
    on_success: change
    on_failure: always
