---
language: generic
dist: trusty
sudo: required
services:
  - docker
env:
  global:
  - secure: "baC0gKKrAW1zMjgQtdl8BpaZ0UmZd9lVevqx9y8nhCSADdsCM1aydsAOq78n5Hi4auXhop9jnsh7OnaDqH6zSBVUYOQ/BlxmqsaAY2RPnDpZZGfmgqqaLohmdMwKPecf8/bWx0fC0t7F6NWiTB+qh1RXYaIif3LixmDEm2Nt9cwWrat69PP1hckzoe4HeOpsEKy1bT3l/5fiKyLsZboVQfVIp/3gg76AJnNd3AReBEgttFBweF01snwqXkzQy9iTRpcPknwBuCUDDQBRnuva3502/ggUX9Wx1t8BTw8aN6n8iTwy5eB+57GDp2iamRe6BuPZ3jSNdzQaAatAjtkH5rpfBSRz4AKwqIA1JJfjiVHh6NG9FSgMprIlOajWaphWy/ZcmqDntdkxPsD4LgwX2RAL5C2Ym3lC3kJD9173Z7VAiA+bEn0z32RIF7KxUqUUEvEDFTh14JS2Q1fXvNdfQfhA3h5GWflUcCU2aW8nSD5f8s94zwXgzz8RTnUwM+RtD+h8EMudmM0Adf4v5/ABj/Kq+w8NnhU3HAsha+qrmQf0IUe85kv7O61qAOl1terHb98O98j+qYbKgdaRrq99Pa4ysMiOv9bb2jqWgRWexbDubu7/p5d98QNrKqCvE/m8ryx7S33cfcvRNDHLjulxgCAbtg/HjqClRhaMtc8Mx1s="
  - secure: "Z8zzNUxplXtwGVno6btYKq68ER7MnYSJBI6hAcMB/liBJYjfNFuKNLReRmpH6J9wqof4Ecy7y14YNZ2wlS/RmRAKYUkYZAbfJJ/90nYs0WOW68EVBDPW4Nhs75IvHm1kQ07kdHbE0W+BZS6utOWsAjrdCp9JFcqIMR6kmkE49jhsYu2KASNpGcdy7lt3kPoIGn5hu3luAfUvIX5oS0yNNCu0VM7JMtCYg07sVHhBCH26TjqoG1nJde9z0ESsHOj1SA4SqLbf9j7ivwDthPgR8JWG5zP6wU4t4tcvN6GIpMqgP4zeThchFmnpdgpzbOxRkiSWhz8IDblsbYrTM/D7mNUXfDDuDtriBtpA9RSs9w2j6h6qaWtXTbOTVa1FhefUioagHXLXr5drV+Qm3bG5w1140yvR6mmVvENhNjbKgYzFH2sgonQzbMCLH1S+eEHSQQx2TStgKyN9rRiNBtTNkvZoFo4eAELyCjwF45FLt3AS94xDvpJXenXnvoo7rKGzLEfhG/PzGrWYdJuJIAuNN7A+5gwV9h+VI5G3a6M5dQQc8BfX+tIxc/AiMrTIeE3mzw06b7XUovmUzrA2+TtORzW3w3ZxYq+TjpmV5nAIyB+BTLLmxmOlRzfj4cCKyUOgeFfmzxDDakHnZV7Opk01s/2hajLHqzjsKR/Kp7VswPE="

before_install:
- docker --version
- docker-compose --version

install:
- curl -L https://goss.rocks/install | sudo sh
- sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- ecs-cli configure profile --profile-name travis --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY
- ecs-cli configure --cluster default --default-launch-type EC2 --region eu-central-1 --config-name travis

script:
- /bin/bash docker/label_containers.sh &&
  docker-compose -p smartzplatform build &&
  /bin/bash ./test/tests.sh &&
  docker images &&
  /bin/bash ./docker/upload_to_registry.sh smartzplatform_frontend smartzplatform_backend

notifications:
  email:
    on_success: change
    on_failure: always
