---
language: bash
dist: trusty
sudo: required
services:
  - docker

install:
  - curl -L https://goss.rocks/install | sudo sh

script:
  - bash ./test/tests.sh

notifications:
  email:
    on_success: change
    on_failure: always
