---
language: generic
dist: trusty
sudo: required
services:
  - docker
env:
  global:
  - secure: "sg5sd6L+U9/9Z2uH875M0p33/T56K6Ey+lc5QAf2XOs2GWTpgJwOBYW2W5AGfTyQxIwk8V/nigaunRW2FGBPPRiF9KeBu31CNHX6Aryg8KCiutTgzhikTKi2kI2hw555zujidRMMc2/M31827N5J3EHDWouhuSE9xNorC6iccPps61tc6MHmcVqPu2f65eWNy1051NbdodMr1vYR6gOFVVEKsDiS5481KJmHyrnhQbNRWoyjt/H/Bxk0lXfh/OxuCUXH+C+uvwuJogPRu40hE1raqjw9X0Buj8KWoujhoIGFmZaHJj4tkLiSOlDqkXkeoh0y0mEqBrkv8sTppBgOc0HRCkG29X3NT3cHf8xvP+owIwHd7hSEcJikBtKKuMzhgmhVJ3xMJBGWwo4aBTQO9CRipEDkxrF314NEvqmpAiwkztsDe4qtpK5j5wfHPLmf85G/MFPTh1RMJRVfBa7Vs0dqK5kT1CVSGBCsNEeEBK5egrp2NyJVP4d9HkKXvbBwSKAPJ1T/1RHvqhbllRDBcpSWsMvFw/tyHi0n13yo5LGssj0Igq3rnp7+C7xQ5pD9RqBIAQkvWowOXqBuPVSQZhkqYXl0jkDZc3LqRJA7WfjhyQxbdnCGOxyUslHS/mbg7ilpXjqPv3S9KXTwjWIZkcOmLyIVaAvX+yToRlifS1E="
  - secure: "mBePMeoEJIMEMCFGGDi5ovuOxPARx/2mZK1HDuDfSeEczjLsSadYxSEiCyl23386DS1eleuiAN5qFJvZdjtuzrWl8beUd/1Il+yFRWn5hI/tWcc79ujQ6K9pac2oDL4V1KwEf8EwyRIVvCKOapvShU3lc0FzEypC4eARNDa1YE7xECq/+lGwc8FO/6NeZTZFgh1JIKAAZQYKHt9WIHY4yKZAa/kBMM5ZYHi0Q2v50StYDEPN7mXRQlbeT5u0eFx0m1iMVBA/hHKXMUPlJXHK5rM0OjANIGJovdOO0mmrmpnh2fnX1KxVMWEwgiXpDIlWlWg64iZtsYjWqbVy99srtuCbHuxeL1amDioepCQMZdlzUoPwRRIh5904JQC3XrkWKW5UE9U0vCZQNkKrQ/RLS2ODnAF5UuMTSv1hmI7JSSEyWF6kSk9vl1fNlNtWPySqzyPZZrWt59crjIG9CiQF5nxitLKMRhM/F0+ILfGo+vKK+Mvg+55hPcN3hNhMlmWIofV11i15l+gXR8sAZSavwrBstw7+nhtYh/whur+cG98AMCNRfkJOsvYF+nUp+Dqh6gajxbOrk09qHqYzC4qVB5oykrYpRK/a8f64fEuio+bzpoPwLWEppqZ3at/xuqvSdUh12YclPmuhu01xUmQEBOWWcTN+e+L6DGtYUWY0X9I="

before_install:
- docker --version
- docker-compose --version

install:
- curl -L https://goss.rocks/install | sudo sh
- sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- ecs-cli configure profile --profile-name travis --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY
- ecs-cli configure --cluster default --default-launch-type EC2 --region eu-central-1 --config-name travis

script:
- /bin/bash docker/label_containers.sh &&
  docker-compose -p smartzplatform build &&
  /bin/bash ./tests/integration.sh &&
  docker images &&
  /bin/bash ./docker/upload_to_registry.sh smartzplatform_frontend smartzplatform_backend

notifications:
  email:
    on_success: change
    on_failure: always
