version: '2'
services:

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "mongodb:/data/db"
    networks:
      - backendnet

  frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
      context: .
      args:
        NGINX_UID: "10000"
    restart: always
    depends_on:
      - backend
      - mongo
    volumes:
      - "backendsocket:/app/sock"
    ports:
      - "8000:80"

  backend:
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
      args:
        UWSGI_UID: "10000"
    restart: always
    volumes:
      - "backendsocket:/app/sock"
    networks:
      - backendnet

volumes:
  backendsocket:
  mongodb:

networks:
  backendnet:
