version: '3.2'
services:

  mongo:
    image: mongo:3.6.3
    restart: "no"
    volumes:
      - "mongodb:/data/db"

  postgres:
    image: postgres:10.3-alpine
    restart: "no"
    env_file:
      - smartzplatform.env
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
      context: .
    env_file:
      - smartzplatform.env
    restart: "no"
    depends_on:
      - backend
    volumes:
      - "backendsocket:/app/sock"
      - "django_static:/static:ro"
    ports:
      - "3000:80"

  backend:
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    env_file:
      - smartzplatform.env
    restart: "no"
    depends_on:
      - mongo
      - postgres
    volumes:
      - "backendsocket:/app/sock"
      - "backenddata:/app/data"
      - "django_static:/static"

volumes:
  backenddata:
  mongodb:
  pgdata:
  django_static:
  backendsocket:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
