version: '2'
services:

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "mongodb:/data/db"

  frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
      context: .
    restart: always
    depends_on:
      - backend
      - mongo
    volumes:
      - "smartz_socket:/app/sock"
    ports:
      - "8000:80"

  backend:
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
      args:
        UWSGI_UID: "100"
    restart: always
    volumes:
      - "smartz_socket:/app/sock"

volumes:
  smartz_socket:
  mongodb:
