file:
  /app:
    exists: true
    mode: "0755"
    owner: root
    group: root
    filetype: directory
    contains: []
  /app/sock:
    exists: true
    mode: "0755"
    owner: root
    group: root
    filetype: directory
    contains: []
port:
  tcp:80:
    listening: true
    ip:
    - 0.0.0.0
user:
  nginx:
    exists: true
    groups:
    - nginx
    home: /var/cache/nginx
    shell: /sbin/nologin
process:
  nginx-debug:
    running: true
