file:
  /app:
    exists: true
    mode: "0755"
    owner: root
    group: root
    filetype: directory
    contains: []
  /app/sock:
    exists: true
    mode: "0755"
    owner: root
    group: root
    filetype: directory
    contains: []
port:
  tcp:80:
    listening: true
    ip:
    - 0.0.0.0
user:
  nginx:
    exists: true
    uid: 10000
    groups:
    - nginx
    home: /var/cache/nginx
    shell: /sbin/nologin
process:
#  nginx:
#    running: false
  nginx-debug:
    running: true
http:
  http://localhost:80:
    status: 200
    timeout: 5000
    body: []
