version: '2'
services:

  mongo:
    image: mongo:3.6.2
    restart: always
    volumes:
      - "mongodb:/data/db"
    networks:
      - backendnet

  frontend:
    image: smartz_frontend:latest
    restart: always
    depends_on:
      - backend
      - mongo
    volumes:
      - "backendsocket:/app/sock"
    ports:
      - "80:80"

  backend:
    image: smartz_backend:latest
    restart: always
    volumes:
      - "backendsocket:/app/sock"
      - "backenddata:/app/data"
    networks:
      - backendnet

volumes:
  backendsocket:
  backenddata:
  mongodb:

networks:
  backendnet:
